version: "3.9"

services:
  server:
    image: sandeshnangare/mern-server:latest
    container_name: mern_server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - mern_network

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/todos || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  client:
    image: sandeshnangare/mern-client:latest
    container_name: mern_client
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    depends_on:
      - server
    restart: always
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge
