apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  labels:
    app: mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
        - name: mern-server
          image: sandeshnangare/mern-server:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mern-secrets
                  key: MONGO_URI
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
