apiVersion: v1
kind: Service
metadata:
  name: mern-backend-service
  labels:
    app: mern-backend
spec:
  selector:
    app: mern-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  # ClusterIP = only accessible inside the cluster
  # The frontend will talk to backend via this service name: mern-backend-service:8000
