apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
  labels:
    app: mern-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      containers:
        - name: mern-client
          image: sandeshnangare/mern-client:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
