name: MERN CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'server/**'
            frontend:
              - 'client/**'

  build-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t sandeshnangare/mern-server:${{ github.sha }} \
          -t sandeshnangare/mern-server:latest \
          ./server \
          --push

  build-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t sandeshnangare/mern-client:${{ github.sha }} \
          -t sandeshnangare/mern-client:latest \
          ./client \
          --push

  deploy:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/mern-cicd-app
            /usr/local/bin/docker-compose pull
            /usr/local/bin/docker-compose down
            /usr/local/bin/docker-compose up -d
